### ISSUE TITLE
Throws exception on queries that don't match anything

### ISSUE THREAD

**Issue by user24** [martijnversluis/JsSuffixTrie#3]
Example: http://jsbin.com/welunisowa/edit?js,console

<pre>
var a= new JsSuffixTrie();
a.add('foo');
a.add('foobar');
a.add('foobum');
console.log(a.find('fuzzle'));
</pre>
<pre>
"TypeError: Cannot read property 'terminator' of null
    at Function.JsSuffixTrie.each (welunisowa.js:92:14)
    at Function.JsSuffixTrie.nodeToArray (welunisowa.js:137:10)
    at JsSuffixTrie.find (welunisowa.js:69:25)
</pre>

I think you just need to add
<pre>
if (node && node.terminator)
</pre>
in JsSuffixTrie.each

**Comment by user24** [comment]
fixed here: https://github.com/user24/JsSuffixTrie/tree/fixEach

Might need other parts of the code fixing to check for null node too.
